const express = require('express')
const request = require('request');
const requestPromise = require('util').promisify(request);

const app = express()
const port = 3000

require('dotenv').config()
const { POW_GAMING__GAME_LIST } = process.env

const LauncherTokenGenerator = require('./lancher-token-generator.js')

require('dotenv').config()
const { POW_GAMING__OPERATOR_ID, POW_GAMING__OPERATOR_SEED, POW_GAMING__POW_SEED, POW_GAMING__PLATFORM_API } = process.env

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

app.get('/game/:gameId', async (req, res) => {
    const gameId = req.params.gameId
    const username = req.query.username
    const userId = username ?? 'randomUser' // generated by the operator
    const operatorId = POW_GAMING__OPERATOR_ID
    const powSeed = POW_GAMING__POW_SEED
    const operatorSeed = POW_GAMING__OPERATOR_SEED
    const launcherTokenGenerator = new LauncherTokenGenerator(operatorId, gameId, userId ,powSeed , operatorSeed)
    launcherTokenGenerator.encode()
    const { body, statusCode } = await requestPromise(`${POW_GAMING__PLATFORM_API}/launch/${launcherTokenGenerator.getLaunchToken()}?call=0`)
    if (statusCode != 200) {
      return res.end('Service unavailable');
    }
    return res.redirect(body)
})

app.get('/game-list.js', async (req, res) => {
  const { body } = await requestPromise(POW_GAMING__GAME_LIST)  
  return res.end(`const gamesList = ${body}`);
})

app.use(express.static('site'));

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})